---

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
    state: present
    cache_valid_time: 3600

- name: Install the Opencast package repository key
  ansible.builtin.apt_key:
    url: https://pkg.opencast.org/gpgkeys/opencast-deb.key
    state: present

- name: Install the Opencast package repository
  ansible.builtin.apt_repository:
    repo: >
      deb https://pkg.opencast.org/debian
      {{ opencast_version_major }}.x
      stable testing
    filename: opencast
    state: present
