---

- name: install dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - gnupg2
    state: present
    cache_valid_time: 3600

- name: install the opencast package repository key
  ansible.builtin.apt_key:
    url: https://pkg.opencast.org/gpgkeys/opencast-deb.key
    state: present

- name: remove orphan opencast package repository definition
  ansible.builtin.apt_repository:
    repo: >-
      deb https://pkg.opencast.org/debian
      {{ opencast_version_major }}.x
      stable testing
    filename: opencast
    state: absent
  notify: update apt cache

- name: install the opencast package repository
  ansible.builtin.apt_repository:
    repo: >-
        deb https://pkg.opencast.org/debian
        {{ opencast_version_major }}.x
        stable
    filename: opencast
    # yamllint disable-line rule:line-length
    state: "{{ 'present' if opencast_repository_enabled_release | bool else 'absent' }}"
  notify: update apt cache

- name: install the opencast testing package repository
  ansible.builtin.apt_repository:
    repo: >-
      deb https://pkg.opencast.org/debian
      {{ opencast_version_major }}.x
      testing
    filename: opencast
    # yamllint disable-line rule:line-length
    state: "{{ 'present' if opencast_repository_enabled_testing | bool else 'absent' }}"
  notify: update apt cache
