---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - gnupg2
    cache_valid_time: 3600

- name: Install the opencast package repository key
  ansible.builtin.apt_key:
    url: https://pkg.opencast.org/gpgkeys/opencast-deb.key
    state: present

- name: Remove orphan opencast package repository definition
  register: rm_orphan_repo
  ansible.builtin.apt_repository:
    repo: >-
      deb https://pkg.opencast.org/debian
      {{ opencast_version_major }}.x
      stable testing
    filename: opencast
    state: absent

- name: Install the opencast package repository
  register: add_oc_repo
  ansible.builtin.apt_repository:
    repo: >-
      deb https://pkg.opencast.org/debian
      {{ opencast_version_major }}.x
      stable
    filename: opencast
    # yamllint disable-line rule:line-length
    state: "{{ 'present' if opencast_repository_enabled_release | bool else 'absent' }}"

- name: Install the opencast testing package repository
  register: add_oc_testing_repo
  ansible.builtin.apt_repository:
    repo: >-
      deb https://pkg.opencast.org/debian
      {{ opencast_version_major }}.x
      testing
    filename: opencast
    # yamllint disable-line rule:line-length
    state: "{{ 'present' if opencast_repository_enabled_testing | bool else 'absent' }}"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: >
    rm_orphan_repo is changed or
    add_oc_repo is changed or
    add_oc_testing_repo is changed
