---
- name: Check that the architecture is supported
  ansible.builtin.assert:
    that: ansible_architecture == "x86_64"

- name: Install on debian/ubuntu
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install on centos
  ansible.builtin.include_tasks: rhel.yml
  when: ansible_os_family == "RedHat"
