---
- name: Converge
  hosts: all
  vars:
    opencast_version_major: 13
    opencast_repository_enabled_release: true
    opencast_repository_enabled_testing: true
  tasks:
    - name: Include opencast_repository
      ansible.builtin.include_role:
        name: opencast_repository
