---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: opencast-repository-centos-9
    image: quay.io/centos/centos:stream9
    pre_build_image: true
  - name: opencast-repository-centos-8
    image: quay.io/centos/centos:stream8
    pre_build_image: true
  - name: opencast-repository-centos-7
    image: docker.io/library/centos:7
    pre_build_image: true
  - name: opencast-repository-debian
    image: docker.io/library/python:bullseye
    pre_build_image: true
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
