---
- name: Verify
  hosts: all
  gather_facts: true
  vars:
    opencast_version_major: 17
  tasks:
    - name: Test if opencast is available
      ansible.builtin.package:
        name: "{{ 'opencast-' + opencast_version_major | string + '-common' if ansible_os_family == 'Debian' else 'opencast' }}"
        state: present
